name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '39 1 3 5 *'
    - cron: '43 4 3 5 *'
    - cron: '15 6 3 5 *'
    - cron: '48 9 3 5 *'
    - cron: '2 12 3 5 *'
    - cron: '14 16 3 5 *'
    - cron: '18 19 3 5 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Git Identity
        run: |
          git config --global user.name "Mehta_Vrushal"
          git config --global user.email "vrushal09@users.noreply.github.com"

      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push